#!/bin/sh

USER_UID=$(id -u)
USER_GID=$(id -g)
BASE_DIR=$(dirname "$0")

sudo docker build -t specific \
                  --build-arg USER_UID="$USER_UID" \
                  --build-arg USER_GID="$USER_GID" \
                  "$BASE_DIR"
