#!/bin/bash

LOCAL_PORT=3000
BASE_DIR=$(dirname "$0")

sudo docker run -ti \
                --rm \
                -v "$(readlink -f "$BASE_DIR"):/opt/service/" \
                -p "$LOCAL_PORT:3000" \
                rails-specific-erb-dev
